//create new database
###

POST http://localhost:3000/api/databases/create-database
Content-Type: application/json

{
    "dbname": "kisbarat"
}

###
// create new user
POST http://localhost:3000/api/databases/create-user
Content-Type: application/json

{
    "username": "csiki",
    "password": "csuki"
}


