// create storage
### 
POST http://localhost:3000/api/storages/create
Content-Type: application/json

{
    "name": "storage1",
    "description": "storage1 description",
    "price": 1000
    
}

// get all storages
###
GET http://localhost:3000/api/storages


//delete storage
###
DELETE http://localhost:3000/api/storages/a1e20cb7-9f3b-45fc-9845-b7fd54d23a6f